spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # User Service - Register (Public)
        - id: user-service-register
          uri: lb://USER-MS
          predicates:
            - Path=/api/users/register
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        
        # User Service - Login (Public)
        - id: user-service-login
          uri: lb://USER-MS
          predicates:
            - Path=/api/users/login
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        
        # Owner Service - Register (Public)
        - id: owner-service-register
          uri: lb://OWNER-MS
          predicates:
            - Path=/api/owners/register
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerFallBack
        
        # Owner Service - Login (Public)
        - id: owner-service-login
          uri: lb://OWNER-MS
          predicates:
            - Path=/api/owners/login
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerFallBack
        
        # User Service Protected Routes (JWT disabled for development)
        - id: user-service-protected
          uri: lb://USER-MS
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        
        # Owner Service Protected Routes (JWT disabled for development)
        - id: owner-service-protected
          uri: lb://OWNER-MS
          predicates:
            - Path=/api/owners/**
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerFallBack
        
        # App Service - Get All Apps (Public)
        - id: app-service-get-all
          uri: lb://APP-MS
          predicates:
            - Path=/api/apps
            - Method=GET
          filters:
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # App Service Routes (now includes Categories, Comments, Downloads, Notifications)
        - id: app-service
          uri: lb://APP-MS
          predicates:
            - Path=/api/apps/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # Category Routes (now handled by App Service)
        - id: category-service
          uri: lb://APP-MS
          predicates:
            - Path=/api/categories/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # Comment Routes (now handled by App Service)
        - id: comment-service
          uri: lb://APP-MS
          predicates:
            - Path=/api/comments/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # Download Routes (now handled by App Service)
        - id: download-service
          uri: lb://APP-MS
          predicates:
            - Path=/api/downloads/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # Notification Routes (now handled by App Service)
        - id: notification-service
          uri: lb://APP-MS
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: app-service
                fallbackuri: forward:/appFallBack
        
        # Legacy HTML Routes (without JWT)
        - id: owner-html
          uri: lb://OWNER-MS
          predicates:
            - Path=/owners/**
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerFallBack
        
        - id: user-html
          uri: lb://USER-MS
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
      
      default-filters:
      - name: CircuitBreaker
        args:
          name: defaultCircuitBreaker
          fallbackUri: forward:/defaultFallback          

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
server:
  port: 8989

app:
  jwt:
    enabled: false
    secret: playStoreSecretKeyForJWTTokenGeneration2023
    expiration: 86400000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000  
            
# JWT Configuration merged with existing app section above

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
      owner-service:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
      app-service:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
      defaultCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50